// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

// Protobuf Java Version: 3.25.0
package art.ameliah.ehb.shortburst.protobuf.impl.adressbook;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.ehb.shortburst.protobuf.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .art.ameliah.ehb.shortburst.protobuf.Person people = 1;</code>
   */
  java.util.List<art.ameliah.ehb.shortburst.protobuf.impl.adressbook.Person> 
      getPeopleList();
  /**
   * <code>repeated .art.ameliah.ehb.shortburst.protobuf.Person people = 1;</code>
   */
  art.ameliah.ehb.shortburst.protobuf.impl.adressbook.Person getPeople(int index);
  /**
   * <code>repeated .art.ameliah.ehb.shortburst.protobuf.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .art.ameliah.ehb.shortburst.protobuf.Person people = 1;</code>
   */
  java.util.List<? extends art.ameliah.ehb.shortburst.protobuf.impl.adressbook.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .art.ameliah.ehb.shortburst.protobuf.Person people = 1;</code>
   */
  art.ameliah.ehb.shortburst.protobuf.impl.adressbook.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
