// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

// Protobuf Java Version: 3.25.0
package art.ameliah.ehb.shortburst.protobuf.impl.adressbook;

public interface AddressBookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.ehb.shortburst.protobuf.AddressBookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .art.ameliah.ehb.shortburst.protobuf.AddressBook book = 1;</code>
   * @return Whether the book field is set.
   */
  boolean hasBook();
  /**
   * <code>optional .art.ameliah.ehb.shortburst.protobuf.AddressBook book = 1;</code>
   * @return The book.
   */
  art.ameliah.ehb.shortburst.protobuf.impl.adressbook.AddressBook getBook();
  /**
   * <code>optional .art.ameliah.ehb.shortburst.protobuf.AddressBook book = 1;</code>
   */
  art.ameliah.ehb.shortburst.protobuf.impl.adressbook.AddressBookOrBuilder getBookOrBuilder();

  /**
   * <code>optional string error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional string error = 3;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 3;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
