// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

// Protobuf Java Version: 3.25.0
package art.ameliah.ehb.shortburst.protobuf.impl.adressbook;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.ehb.shortburst.protobuf.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .art.ameliah.ehb.shortburst.protobuf.Person person = 1;</code>
   * @return Whether the person field is set.
   */
  boolean hasPerson();
  /**
   * <code>optional .art.ameliah.ehb.shortburst.protobuf.Person person = 1;</code>
   * @return The person.
   */
  art.ameliah.ehb.shortburst.protobuf.impl.adressbook.Person getPerson();
  /**
   * <code>optional .art.ameliah.ehb.shortburst.protobuf.Person person = 1;</code>
   */
  art.ameliah.ehb.shortburst.protobuf.impl.adressbook.PersonOrBuilder getPersonOrBuilder();

  /**
   * <code>optional string error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional string error = 3;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 3;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
