// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

// Protobuf Java Version: 3.25.0
package art.ameliah.ehb.shortburst.protobuf.impl.adressbook;

public interface UploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.ehb.shortburst.protobuf.UploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional string error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional string error = 3;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 3;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
