// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public interface APIClientMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.pulsewatcher.APIClientMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host = 1;</code>
   * @return The host.
   */
  java.lang.String getHost();
  /**
   * <code>string host = 1;</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>string os = 2;</code>
   * @return The os.
   */
  java.lang.String getOs();
  /**
   * <code>string os = 2;</code>
   * @return The bytes for os.
   */
  com.google.protobuf.ByteString
      getOsBytes();

  /**
   * <code>string port = 3;</code>
   * @return The port.
   */
  java.lang.String getPort();
  /**
   * <code>string port = 3;</code>
   * @return The bytes for port.
   */
  com.google.protobuf.ByteString
      getPortBytes();

  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  java.util.List<art.ameliah.pulsewatcher.proto.APIEndPointMetric> 
      getApiEndPointMetricsList();
  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  art.ameliah.pulsewatcher.proto.APIEndPointMetric getApiEndPointMetrics(int index);
  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  int getApiEndPointMetricsCount();
  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  java.util.List<? extends art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder> 
      getApiEndPointMetricsOrBuilderList();
  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder getApiEndPointMetricsOrBuilder(
      int index);
}
