// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

/**
 * Protobuf type {@code art.ameliah.pulsewatcher.APIClientMetric}
 */
public final class APIClientMetric extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:art.ameliah.pulsewatcher.APIClientMetric)
    APIClientMetricOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APIClientMetric.newBuilder() to construct.
  private APIClientMetric(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APIClientMetric() {
    host_ = "";
    os_ = "";
    port_ = "";
    apiEndPointMetrics_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new APIClientMetric();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIClientMetric_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIClientMetric_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            art.ameliah.pulsewatcher.proto.APIClientMetric.class, art.ameliah.pulsewatcher.proto.APIClientMetric.Builder.class);
  }

  public static final int HOST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object host_ = "";
  /**
   * <code>string host = 1;</code>
   * @return The host.
   */
  @java.lang.Override
  public java.lang.String getHost() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      host_ = s;
      return s;
    }
  }
  /**
   * <code>string host = 1;</code>
   * @return The bytes for host.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostBytes() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      host_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object os_ = "";
  /**
   * <code>string os = 2;</code>
   * @return The os.
   */
  @java.lang.Override
  public java.lang.String getOs() {
    java.lang.Object ref = os_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      os_ = s;
      return s;
    }
  }
  /**
   * <code>string os = 2;</code>
   * @return The bytes for os.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsBytes() {
    java.lang.Object ref = os_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      os_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object port_ = "";
  /**
   * <code>string port = 3;</code>
   * @return The port.
   */
  @java.lang.Override
  public java.lang.String getPort() {
    java.lang.Object ref = port_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      port_ = s;
      return s;
    }
  }
  /**
   * <code>string port = 3;</code>
   * @return The bytes for port.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPortBytes() {
    java.lang.Object ref = port_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      port_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APIENDPOINTMETRICS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<art.ameliah.pulsewatcher.proto.APIEndPointMetric> apiEndPointMetrics_;
  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  @java.lang.Override
  public java.util.List<art.ameliah.pulsewatcher.proto.APIEndPointMetric> getApiEndPointMetricsList() {
    return apiEndPointMetrics_;
  }
  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder> 
      getApiEndPointMetricsOrBuilderList() {
    return apiEndPointMetrics_;
  }
  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  @java.lang.Override
  public int getApiEndPointMetricsCount() {
    return apiEndPointMetrics_.size();
  }
  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.APIEndPointMetric getApiEndPointMetrics(int index) {
    return apiEndPointMetrics_.get(index);
  }
  /**
   * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder getApiEndPointMetricsOrBuilder(
      int index) {
    return apiEndPointMetrics_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(os_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, os_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(port_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, port_);
    }
    for (int i = 0; i < apiEndPointMetrics_.size(); i++) {
      output.writeMessage(4, apiEndPointMetrics_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(os_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, os_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(port_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, port_);
    }
    for (int i = 0; i < apiEndPointMetrics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, apiEndPointMetrics_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof art.ameliah.pulsewatcher.proto.APIClientMetric)) {
      return super.equals(obj);
    }
    art.ameliah.pulsewatcher.proto.APIClientMetric other = (art.ameliah.pulsewatcher.proto.APIClientMetric) obj;

    if (!getHost()
        .equals(other.getHost())) return false;
    if (!getOs()
        .equals(other.getOs())) return false;
    if (!getPort()
        .equals(other.getPort())) return false;
    if (!getApiEndPointMetricsList()
        .equals(other.getApiEndPointMetricsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOST_FIELD_NUMBER;
    hash = (53 * hash) + getHost().hashCode();
    hash = (37 * hash) + OS_FIELD_NUMBER;
    hash = (53 * hash) + getOs().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort().hashCode();
    if (getApiEndPointMetricsCount() > 0) {
      hash = (37 * hash) + APIENDPOINTMETRICS_FIELD_NUMBER;
      hash = (53 * hash) + getApiEndPointMetricsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.APIClientMetric parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(art.ameliah.pulsewatcher.proto.APIClientMetric prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code art.ameliah.pulsewatcher.APIClientMetric}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:art.ameliah.pulsewatcher.APIClientMetric)
      art.ameliah.pulsewatcher.proto.APIClientMetricOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIClientMetric_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIClientMetric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              art.ameliah.pulsewatcher.proto.APIClientMetric.class, art.ameliah.pulsewatcher.proto.APIClientMetric.Builder.class);
    }

    // Construct using art.ameliah.pulsewatcher.proto.APIClientMetric.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      host_ = "";
      os_ = "";
      port_ = "";
      if (apiEndPointMetricsBuilder_ == null) {
        apiEndPointMetrics_ = java.util.Collections.emptyList();
      } else {
        apiEndPointMetrics_ = null;
        apiEndPointMetricsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIClientMetric_descriptor;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.APIClientMetric getDefaultInstanceForType() {
      return art.ameliah.pulsewatcher.proto.APIClientMetric.getDefaultInstance();
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.APIClientMetric build() {
      art.ameliah.pulsewatcher.proto.APIClientMetric result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.APIClientMetric buildPartial() {
      art.ameliah.pulsewatcher.proto.APIClientMetric result = new art.ameliah.pulsewatcher.proto.APIClientMetric(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(art.ameliah.pulsewatcher.proto.APIClientMetric result) {
      if (apiEndPointMetricsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          apiEndPointMetrics_ = java.util.Collections.unmodifiableList(apiEndPointMetrics_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.apiEndPointMetrics_ = apiEndPointMetrics_;
      } else {
        result.apiEndPointMetrics_ = apiEndPointMetricsBuilder_.build();
      }
    }

    private void buildPartial0(art.ameliah.pulsewatcher.proto.APIClientMetric result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.host_ = host_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.os_ = os_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.port_ = port_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof art.ameliah.pulsewatcher.proto.APIClientMetric) {
        return mergeFrom((art.ameliah.pulsewatcher.proto.APIClientMetric)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(art.ameliah.pulsewatcher.proto.APIClientMetric other) {
      if (other == art.ameliah.pulsewatcher.proto.APIClientMetric.getDefaultInstance()) return this;
      if (!other.getHost().isEmpty()) {
        host_ = other.host_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getOs().isEmpty()) {
        os_ = other.os_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPort().isEmpty()) {
        port_ = other.port_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (apiEndPointMetricsBuilder_ == null) {
        if (!other.apiEndPointMetrics_.isEmpty()) {
          if (apiEndPointMetrics_.isEmpty()) {
            apiEndPointMetrics_ = other.apiEndPointMetrics_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureApiEndPointMetricsIsMutable();
            apiEndPointMetrics_.addAll(other.apiEndPointMetrics_);
          }
          onChanged();
        }
      } else {
        if (!other.apiEndPointMetrics_.isEmpty()) {
          if (apiEndPointMetricsBuilder_.isEmpty()) {
            apiEndPointMetricsBuilder_.dispose();
            apiEndPointMetricsBuilder_ = null;
            apiEndPointMetrics_ = other.apiEndPointMetrics_;
            bitField0_ = (bitField0_ & ~0x00000008);
            apiEndPointMetricsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getApiEndPointMetricsFieldBuilder() : null;
          } else {
            apiEndPointMetricsBuilder_.addAllMessages(other.apiEndPointMetrics_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              host_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              os_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              port_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              art.ameliah.pulsewatcher.proto.APIEndPointMetric m =
                  input.readMessage(
                      art.ameliah.pulsewatcher.proto.APIEndPointMetric.parser(),
                      extensionRegistry);
              if (apiEndPointMetricsBuilder_ == null) {
                ensureApiEndPointMetricsIsMutable();
                apiEndPointMetrics_.add(m);
              } else {
                apiEndPointMetricsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object host_ = "";
    /**
     * <code>string host = 1;</code>
     * @return The host.
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string host = 1;</code>
     * @return The bytes for host.
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string host = 1;</code>
     * @param value The host to set.
     * @return This builder for chaining.
     */
    public Builder setHost(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      host_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string host = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHost() {
      host_ = getDefaultInstance().getHost();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string host = 1;</code>
     * @param value The bytes for host to set.
     * @return This builder for chaining.
     */
    public Builder setHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      host_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object os_ = "";
    /**
     * <code>string os = 2;</code>
     * @return The os.
     */
    public java.lang.String getOs() {
      java.lang.Object ref = os_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        os_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string os = 2;</code>
     * @return The bytes for os.
     */
    public com.google.protobuf.ByteString
        getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string os = 2;</code>
     * @param value The os to set.
     * @return This builder for chaining.
     */
    public Builder setOs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      os_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string os = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOs() {
      os_ = getDefaultInstance().getOs();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string os = 2;</code>
     * @param value The bytes for os to set.
     * @return This builder for chaining.
     */
    public Builder setOsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      os_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object port_ = "";
    /**
     * <code>string port = 3;</code>
     * @return The port.
     */
    public java.lang.String getPort() {
      java.lang.Object ref = port_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        port_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string port = 3;</code>
     * @return The bytes for port.
     */
    public com.google.protobuf.ByteString
        getPortBytes() {
      java.lang.Object ref = port_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        port_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string port = 3;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      port_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string port = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {
      port_ = getDefaultInstance().getPort();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string port = 3;</code>
     * @param value The bytes for port to set.
     * @return This builder for chaining.
     */
    public Builder setPortBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      port_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<art.ameliah.pulsewatcher.proto.APIEndPointMetric> apiEndPointMetrics_ =
      java.util.Collections.emptyList();
    private void ensureApiEndPointMetricsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        apiEndPointMetrics_ = new java.util.ArrayList<art.ameliah.pulsewatcher.proto.APIEndPointMetric>(apiEndPointMetrics_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.APIEndPointMetric, art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder, art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder> apiEndPointMetricsBuilder_;

    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public java.util.List<art.ameliah.pulsewatcher.proto.APIEndPointMetric> getApiEndPointMetricsList() {
      if (apiEndPointMetricsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(apiEndPointMetrics_);
      } else {
        return apiEndPointMetricsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public int getApiEndPointMetricsCount() {
      if (apiEndPointMetricsBuilder_ == null) {
        return apiEndPointMetrics_.size();
      } else {
        return apiEndPointMetricsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public art.ameliah.pulsewatcher.proto.APIEndPointMetric getApiEndPointMetrics(int index) {
      if (apiEndPointMetricsBuilder_ == null) {
        return apiEndPointMetrics_.get(index);
      } else {
        return apiEndPointMetricsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public Builder setApiEndPointMetrics(
        int index, art.ameliah.pulsewatcher.proto.APIEndPointMetric value) {
      if (apiEndPointMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApiEndPointMetricsIsMutable();
        apiEndPointMetrics_.set(index, value);
        onChanged();
      } else {
        apiEndPointMetricsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public Builder setApiEndPointMetrics(
        int index, art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder builderForValue) {
      if (apiEndPointMetricsBuilder_ == null) {
        ensureApiEndPointMetricsIsMutable();
        apiEndPointMetrics_.set(index, builderForValue.build());
        onChanged();
      } else {
        apiEndPointMetricsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public Builder addApiEndPointMetrics(art.ameliah.pulsewatcher.proto.APIEndPointMetric value) {
      if (apiEndPointMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApiEndPointMetricsIsMutable();
        apiEndPointMetrics_.add(value);
        onChanged();
      } else {
        apiEndPointMetricsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public Builder addApiEndPointMetrics(
        int index, art.ameliah.pulsewatcher.proto.APIEndPointMetric value) {
      if (apiEndPointMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureApiEndPointMetricsIsMutable();
        apiEndPointMetrics_.add(index, value);
        onChanged();
      } else {
        apiEndPointMetricsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public Builder addApiEndPointMetrics(
        art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder builderForValue) {
      if (apiEndPointMetricsBuilder_ == null) {
        ensureApiEndPointMetricsIsMutable();
        apiEndPointMetrics_.add(builderForValue.build());
        onChanged();
      } else {
        apiEndPointMetricsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public Builder addApiEndPointMetrics(
        int index, art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder builderForValue) {
      if (apiEndPointMetricsBuilder_ == null) {
        ensureApiEndPointMetricsIsMutable();
        apiEndPointMetrics_.add(index, builderForValue.build());
        onChanged();
      } else {
        apiEndPointMetricsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public Builder addAllApiEndPointMetrics(
        java.lang.Iterable<? extends art.ameliah.pulsewatcher.proto.APIEndPointMetric> values) {
      if (apiEndPointMetricsBuilder_ == null) {
        ensureApiEndPointMetricsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, apiEndPointMetrics_);
        onChanged();
      } else {
        apiEndPointMetricsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public Builder clearApiEndPointMetrics() {
      if (apiEndPointMetricsBuilder_ == null) {
        apiEndPointMetrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        apiEndPointMetricsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public Builder removeApiEndPointMetrics(int index) {
      if (apiEndPointMetricsBuilder_ == null) {
        ensureApiEndPointMetricsIsMutable();
        apiEndPointMetrics_.remove(index);
        onChanged();
      } else {
        apiEndPointMetricsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder getApiEndPointMetricsBuilder(
        int index) {
      return getApiEndPointMetricsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder getApiEndPointMetricsOrBuilder(
        int index) {
      if (apiEndPointMetricsBuilder_ == null) {
        return apiEndPointMetrics_.get(index);  } else {
        return apiEndPointMetricsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public java.util.List<? extends art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder> 
         getApiEndPointMetricsOrBuilderList() {
      if (apiEndPointMetricsBuilder_ != null) {
        return apiEndPointMetricsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(apiEndPointMetrics_);
      }
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder addApiEndPointMetricsBuilder() {
      return getApiEndPointMetricsFieldBuilder().addBuilder(
          art.ameliah.pulsewatcher.proto.APIEndPointMetric.getDefaultInstance());
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder addApiEndPointMetricsBuilder(
        int index) {
      return getApiEndPointMetricsFieldBuilder().addBuilder(
          index, art.ameliah.pulsewatcher.proto.APIEndPointMetric.getDefaultInstance());
    }
    /**
     * <code>repeated .art.ameliah.pulsewatcher.APIEndPointMetric apiEndPointMetrics = 4;</code>
     */
    public java.util.List<art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder> 
         getApiEndPointMetricsBuilderList() {
      return getApiEndPointMetricsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.APIEndPointMetric, art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder, art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder> 
        getApiEndPointMetricsFieldBuilder() {
      if (apiEndPointMetricsBuilder_ == null) {
        apiEndPointMetricsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            art.ameliah.pulsewatcher.proto.APIEndPointMetric, art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder, art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder>(
                apiEndPointMetrics_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        apiEndPointMetrics_ = null;
      }
      return apiEndPointMetricsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:art.ameliah.pulsewatcher.APIClientMetric)
  }

  // @@protoc_insertion_point(class_scope:art.ameliah.pulsewatcher.APIClientMetric)
  private static final art.ameliah.pulsewatcher.proto.APIClientMetric DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new art.ameliah.pulsewatcher.proto.APIClientMetric();
  }

  public static art.ameliah.pulsewatcher.proto.APIClientMetric getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<APIClientMetric>
      PARSER = new com.google.protobuf.AbstractParser<APIClientMetric>() {
    @java.lang.Override
    public APIClientMetric parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<APIClientMetric> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APIClientMetric> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.APIClientMetric getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

