// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

/**
 * Protobuf type {@code art.ameliah.pulsewatcher.APIEndPointMetric}
 */
public final class APIEndPointMetric extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:art.ameliah.pulsewatcher.APIEndPointMetric)
    APIEndPointMetricOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APIEndPointMetric.newBuilder() to construct.
  private APIEndPointMetric(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APIEndPointMetric() {
    endPoint_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new APIEndPointMetric();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            art.ameliah.pulsewatcher.proto.APIEndPointMetric.class, art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder.class);
  }

  public static final int ENDPOINT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object endPoint_ = "";
  /**
   * <code>string endPoint = 1;</code>
   * @return The endPoint.
   */
  @java.lang.Override
  public java.lang.String getEndPoint() {
    java.lang.Object ref = endPoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endPoint_ = s;
      return s;
    }
  }
  /**
   * <code>string endPoint = 1;</code>
   * @return The bytes for endPoint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEndPointBytes() {
    java.lang.Object ref = endPoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endPoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HITS_FIELD_NUMBER = 2;
  private long hits_ = 0L;
  /**
   * <code>int64 hits = 2;</code>
   * @return The hits.
   */
  @java.lang.Override
  public long getHits() {
    return hits_;
  }

  public static final int ERRORS_FIELD_NUMBER = 3;
  private long errors_ = 0L;
  /**
   * <code>int64 errors = 3;</code>
   * @return The errors.
   */
  @java.lang.Override
  public long getErrors() {
    return errors_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endPoint_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, endPoint_);
    }
    if (hits_ != 0L) {
      output.writeInt64(2, hits_);
    }
    if (errors_ != 0L) {
      output.writeInt64(3, errors_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endPoint_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, endPoint_);
    }
    if (hits_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, hits_);
    }
    if (errors_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, errors_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof art.ameliah.pulsewatcher.proto.APIEndPointMetric)) {
      return super.equals(obj);
    }
    art.ameliah.pulsewatcher.proto.APIEndPointMetric other = (art.ameliah.pulsewatcher.proto.APIEndPointMetric) obj;

    if (!getEndPoint()
        .equals(other.getEndPoint())) return false;
    if (getHits()
        != other.getHits()) return false;
    if (getErrors()
        != other.getErrors()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENDPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getEndPoint().hashCode();
    hash = (37 * hash) + HITS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHits());
    hash = (37 * hash) + ERRORS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getErrors());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(art.ameliah.pulsewatcher.proto.APIEndPointMetric prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code art.ameliah.pulsewatcher.APIEndPointMetric}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:art.ameliah.pulsewatcher.APIEndPointMetric)
      art.ameliah.pulsewatcher.proto.APIEndPointMetricOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              art.ameliah.pulsewatcher.proto.APIEndPointMetric.class, art.ameliah.pulsewatcher.proto.APIEndPointMetric.Builder.class);
    }

    // Construct using art.ameliah.pulsewatcher.proto.APIEndPointMetric.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      endPoint_ = "";
      hits_ = 0L;
      errors_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_descriptor;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.APIEndPointMetric getDefaultInstanceForType() {
      return art.ameliah.pulsewatcher.proto.APIEndPointMetric.getDefaultInstance();
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.APIEndPointMetric build() {
      art.ameliah.pulsewatcher.proto.APIEndPointMetric result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.APIEndPointMetric buildPartial() {
      art.ameliah.pulsewatcher.proto.APIEndPointMetric result = new art.ameliah.pulsewatcher.proto.APIEndPointMetric(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(art.ameliah.pulsewatcher.proto.APIEndPointMetric result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.endPoint_ = endPoint_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hits_ = hits_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.errors_ = errors_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof art.ameliah.pulsewatcher.proto.APIEndPointMetric) {
        return mergeFrom((art.ameliah.pulsewatcher.proto.APIEndPointMetric)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(art.ameliah.pulsewatcher.proto.APIEndPointMetric other) {
      if (other == art.ameliah.pulsewatcher.proto.APIEndPointMetric.getDefaultInstance()) return this;
      if (!other.getEndPoint().isEmpty()) {
        endPoint_ = other.endPoint_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getHits() != 0L) {
        setHits(other.getHits());
      }
      if (other.getErrors() != 0L) {
        setErrors(other.getErrors());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              endPoint_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              hits_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              errors_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object endPoint_ = "";
    /**
     * <code>string endPoint = 1;</code>
     * @return The endPoint.
     */
    public java.lang.String getEndPoint() {
      java.lang.Object ref = endPoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endPoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string endPoint = 1;</code>
     * @return The bytes for endPoint.
     */
    public com.google.protobuf.ByteString
        getEndPointBytes() {
      java.lang.Object ref = endPoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endPoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string endPoint = 1;</code>
     * @param value The endPoint to set.
     * @return This builder for chaining.
     */
    public Builder setEndPoint(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      endPoint_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string endPoint = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndPoint() {
      endPoint_ = getDefaultInstance().getEndPoint();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string endPoint = 1;</code>
     * @param value The bytes for endPoint to set.
     * @return This builder for chaining.
     */
    public Builder setEndPointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      endPoint_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long hits_ ;
    /**
     * <code>int64 hits = 2;</code>
     * @return The hits.
     */
    @java.lang.Override
    public long getHits() {
      return hits_;
    }
    /**
     * <code>int64 hits = 2;</code>
     * @param value The hits to set.
     * @return This builder for chaining.
     */
    public Builder setHits(long value) {

      hits_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 hits = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHits() {
      bitField0_ = (bitField0_ & ~0x00000002);
      hits_ = 0L;
      onChanged();
      return this;
    }

    private long errors_ ;
    /**
     * <code>int64 errors = 3;</code>
     * @return The errors.
     */
    @java.lang.Override
    public long getErrors() {
      return errors_;
    }
    /**
     * <code>int64 errors = 3;</code>
     * @param value The errors to set.
     * @return This builder for chaining.
     */
    public Builder setErrors(long value) {

      errors_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 errors = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrors() {
      bitField0_ = (bitField0_ & ~0x00000004);
      errors_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:art.ameliah.pulsewatcher.APIEndPointMetric)
  }

  // @@protoc_insertion_point(class_scope:art.ameliah.pulsewatcher.APIEndPointMetric)
  private static final art.ameliah.pulsewatcher.proto.APIEndPointMetric DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new art.ameliah.pulsewatcher.proto.APIEndPointMetric();
  }

  public static art.ameliah.pulsewatcher.proto.APIEndPointMetric getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<APIEndPointMetric>
      PARSER = new com.google.protobuf.AbstractParser<APIEndPointMetric>() {
    @java.lang.Override
    public APIEndPointMetric parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<APIEndPointMetric> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APIEndPointMetric> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.APIEndPointMetric getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

