// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public interface APIEndPointMetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.pulsewatcher.APIEndPointMetric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string endPoint = 1;</code>
   * @return The endPoint.
   */
  java.lang.String getEndPoint();
  /**
   * <code>string endPoint = 1;</code>
   * @return The bytes for endPoint.
   */
  com.google.protobuf.ByteString
      getEndPointBytes();

  /**
   * <code>int64 hits = 2;</code>
   * @return The hits.
   */
  long getHits();

  /**
   * <code>int64 errors = 3;</code>
   * @return The errors.
   */
  long getErrors();
}
