// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public interface C2SConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.pulsewatcher.C2SConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .art.ameliah.pulsewatcher.ConfigField fields = 1;</code>
   */
  java.util.List<art.ameliah.pulsewatcher.proto.ConfigField> 
      getFieldsList();
  /**
   * <code>repeated .art.ameliah.pulsewatcher.ConfigField fields = 1;</code>
   */
  art.ameliah.pulsewatcher.proto.ConfigField getFields(int index);
  /**
   * <code>repeated .art.ameliah.pulsewatcher.ConfigField fields = 1;</code>
   */
  int getFieldsCount();
  /**
   * <code>repeated .art.ameliah.pulsewatcher.ConfigField fields = 1;</code>
   */
  java.util.List<? extends art.ameliah.pulsewatcher.proto.ConfigFieldOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <code>repeated .art.ameliah.pulsewatcher.ConfigField fields = 1;</code>
   */
  art.ameliah.pulsewatcher.proto.ConfigFieldOrBuilder getFieldsOrBuilder(
      int index);

  /**
   * <code>repeated .art.ameliah.pulsewatcher.MutableConfigField mutableFields = 2;</code>
   */
  java.util.List<art.ameliah.pulsewatcher.proto.MutableConfigField> 
      getMutableFieldsList();
  /**
   * <code>repeated .art.ameliah.pulsewatcher.MutableConfigField mutableFields = 2;</code>
   */
  art.ameliah.pulsewatcher.proto.MutableConfigField getMutableFields(int index);
  /**
   * <code>repeated .art.ameliah.pulsewatcher.MutableConfigField mutableFields = 2;</code>
   */
  int getMutableFieldsCount();
  /**
   * <code>repeated .art.ameliah.pulsewatcher.MutableConfigField mutableFields = 2;</code>
   */
  java.util.List<? extends art.ameliah.pulsewatcher.proto.MutableConfigFieldOrBuilder> 
      getMutableFieldsOrBuilderList();
  /**
   * <code>repeated .art.ameliah.pulsewatcher.MutableConfigField mutableFields = 2;</code>
   */
  art.ameliah.pulsewatcher.proto.MutableConfigFieldOrBuilder getMutableFieldsOrBuilder(
      int index);
}
