// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public interface C2SMetricPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.pulsewatcher.C2SMetricPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 ramUsage = 1;</code>
   * @return The ramUsage.
   */
  long getRamUsage();

  /**
   * <code>int64 uptime = 2;</code>
   * @return The uptime.
   */
  long getUptime();

  /**
   * <code>.art.ameliah.pulsewatcher.APIClientMetric apiClientMetric = 3;</code>
   * @return Whether the apiClientMetric field is set.
   */
  boolean hasApiClientMetric();
  /**
   * <code>.art.ameliah.pulsewatcher.APIClientMetric apiClientMetric = 3;</code>
   * @return The apiClientMetric.
   */
  art.ameliah.pulsewatcher.proto.APIClientMetric getApiClientMetric();
  /**
   * <code>.art.ameliah.pulsewatcher.APIClientMetric apiClientMetric = 3;</code>
   */
  art.ameliah.pulsewatcher.proto.APIClientMetricOrBuilder getApiClientMetricOrBuilder();

  art.ameliah.pulsewatcher.proto.C2SMetricPacket.MetricsCase getMetricsCase();
}
