// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public interface C2SPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.pulsewatcher.C2SPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
   * @return Whether the registerPacket field is set.
   */
  boolean hasRegisterPacket();
  /**
   * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
   * @return The registerPacket.
   */
  art.ameliah.pulsewatcher.proto.C2SRegisterPacket getRegisterPacket();
  /**
   * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
   */
  art.ameliah.pulsewatcher.proto.C2SRegisterPacketOrBuilder getRegisterPacketOrBuilder();

  /**
   * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
   * @return Whether the pingPacket field is set.
   */
  boolean hasPingPacket();
  /**
   * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
   * @return The pingPacket.
   */
  art.ameliah.pulsewatcher.proto.C2SPingPacket getPingPacket();
  /**
   * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
   */
  art.ameliah.pulsewatcher.proto.C2SPingPacketOrBuilder getPingPacketOrBuilder();

  /**
   * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
   * @return Whether the metricPacket field is set.
   */
  boolean hasMetricPacket();
  /**
   * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
   * @return The metricPacket.
   */
  art.ameliah.pulsewatcher.proto.C2SMetricPacket getMetricPacket();
  /**
   * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
   */
  art.ameliah.pulsewatcher.proto.C2SMetricPacketOrBuilder getMetricPacketOrBuilder();

  art.ameliah.pulsewatcher.proto.C2SPacket.PacketCase getPacketCase();
}
