// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

/**
 * Protobuf type {@code art.ameliah.pulsewatcher.C2SPacket}
 */
public final class C2SPacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:art.ameliah.pulsewatcher.C2SPacket)
    C2SPacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use C2SPacket.newBuilder() to construct.
  private C2SPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private C2SPacket() {
    token_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new C2SPacket();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_C2SPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_C2SPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            art.ameliah.pulsewatcher.proto.C2SPacket.class, art.ameliah.pulsewatcher.proto.C2SPacket.Builder.class);
  }

  private int packetCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object packet_;
  public enum PacketCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    REGISTERPACKET(2),
    PINGPACKET(3),
    METRICPACKET(4),
    PACKET_NOT_SET(0);
    private final int value;
    private PacketCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketCase valueOf(int value) {
      return forNumber(value);
    }

    public static PacketCase forNumber(int value) {
      switch (value) {
        case 2: return REGISTERPACKET;
        case 3: return PINGPACKET;
        case 4: return METRICPACKET;
        case 0: return PACKET_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PacketCase
  getPacketCase() {
    return PacketCase.forNumber(
        packetCase_);
  }

  public static final int TOKEN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object token_ = "";
  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGISTERPACKET_FIELD_NUMBER = 2;
  /**
   * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
   * @return Whether the registerPacket field is set.
   */
  @java.lang.Override
  public boolean hasRegisterPacket() {
    return packetCase_ == 2;
  }
  /**
   * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
   * @return The registerPacket.
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.C2SRegisterPacket getRegisterPacket() {
    if (packetCase_ == 2) {
       return (art.ameliah.pulsewatcher.proto.C2SRegisterPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.C2SRegisterPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.C2SRegisterPacketOrBuilder getRegisterPacketOrBuilder() {
    if (packetCase_ == 2) {
       return (art.ameliah.pulsewatcher.proto.C2SRegisterPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.C2SRegisterPacket.getDefaultInstance();
  }

  public static final int PINGPACKET_FIELD_NUMBER = 3;
  /**
   * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
   * @return Whether the pingPacket field is set.
   */
  @java.lang.Override
  public boolean hasPingPacket() {
    return packetCase_ == 3;
  }
  /**
   * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
   * @return The pingPacket.
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.C2SPingPacket getPingPacket() {
    if (packetCase_ == 3) {
       return (art.ameliah.pulsewatcher.proto.C2SPingPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.C2SPingPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.C2SPingPacketOrBuilder getPingPacketOrBuilder() {
    if (packetCase_ == 3) {
       return (art.ameliah.pulsewatcher.proto.C2SPingPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.C2SPingPacket.getDefaultInstance();
  }

  public static final int METRICPACKET_FIELD_NUMBER = 4;
  /**
   * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
   * @return Whether the metricPacket field is set.
   */
  @java.lang.Override
  public boolean hasMetricPacket() {
    return packetCase_ == 4;
  }
  /**
   * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
   * @return The metricPacket.
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.C2SMetricPacket getMetricPacket() {
    if (packetCase_ == 4) {
       return (art.ameliah.pulsewatcher.proto.C2SMetricPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.C2SMetricPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.C2SMetricPacketOrBuilder getMetricPacketOrBuilder() {
    if (packetCase_ == 4) {
       return (art.ameliah.pulsewatcher.proto.C2SMetricPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.C2SMetricPacket.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
    }
    if (packetCase_ == 2) {
      output.writeMessage(2, (art.ameliah.pulsewatcher.proto.C2SRegisterPacket) packet_);
    }
    if (packetCase_ == 3) {
      output.writeMessage(3, (art.ameliah.pulsewatcher.proto.C2SPingPacket) packet_);
    }
    if (packetCase_ == 4) {
      output.writeMessage(4, (art.ameliah.pulsewatcher.proto.C2SMetricPacket) packet_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
    }
    if (packetCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (art.ameliah.pulsewatcher.proto.C2SRegisterPacket) packet_);
    }
    if (packetCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (art.ameliah.pulsewatcher.proto.C2SPingPacket) packet_);
    }
    if (packetCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (art.ameliah.pulsewatcher.proto.C2SMetricPacket) packet_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof art.ameliah.pulsewatcher.proto.C2SPacket)) {
      return super.equals(obj);
    }
    art.ameliah.pulsewatcher.proto.C2SPacket other = (art.ameliah.pulsewatcher.proto.C2SPacket) obj;

    if (!getToken()
        .equals(other.getToken())) return false;
    if (!getPacketCase().equals(other.getPacketCase())) return false;
    switch (packetCase_) {
      case 2:
        if (!getRegisterPacket()
            .equals(other.getRegisterPacket())) return false;
        break;
      case 3:
        if (!getPingPacket()
            .equals(other.getPingPacket())) return false;
        break;
      case 4:
        if (!getMetricPacket()
            .equals(other.getMetricPacket())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    switch (packetCase_) {
      case 2:
        hash = (37 * hash) + REGISTERPACKET_FIELD_NUMBER;
        hash = (53 * hash) + getRegisterPacket().hashCode();
        break;
      case 3:
        hash = (37 * hash) + PINGPACKET_FIELD_NUMBER;
        hash = (53 * hash) + getPingPacket().hashCode();
        break;
      case 4:
        hash = (37 * hash) + METRICPACKET_FIELD_NUMBER;
        hash = (53 * hash) + getMetricPacket().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static art.ameliah.pulsewatcher.proto.C2SPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static art.ameliah.pulsewatcher.proto.C2SPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.C2SPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(art.ameliah.pulsewatcher.proto.C2SPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code art.ameliah.pulsewatcher.C2SPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:art.ameliah.pulsewatcher.C2SPacket)
      art.ameliah.pulsewatcher.proto.C2SPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_C2SPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_C2SPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              art.ameliah.pulsewatcher.proto.C2SPacket.class, art.ameliah.pulsewatcher.proto.C2SPacket.Builder.class);
    }

    // Construct using art.ameliah.pulsewatcher.proto.C2SPacket.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      token_ = "";
      if (registerPacketBuilder_ != null) {
        registerPacketBuilder_.clear();
      }
      if (pingPacketBuilder_ != null) {
        pingPacketBuilder_.clear();
      }
      if (metricPacketBuilder_ != null) {
        metricPacketBuilder_.clear();
      }
      packetCase_ = 0;
      packet_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_C2SPacket_descriptor;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.C2SPacket getDefaultInstanceForType() {
      return art.ameliah.pulsewatcher.proto.C2SPacket.getDefaultInstance();
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.C2SPacket build() {
      art.ameliah.pulsewatcher.proto.C2SPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.C2SPacket buildPartial() {
      art.ameliah.pulsewatcher.proto.C2SPacket result = new art.ameliah.pulsewatcher.proto.C2SPacket(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(art.ameliah.pulsewatcher.proto.C2SPacket result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.token_ = token_;
      }
    }

    private void buildPartialOneofs(art.ameliah.pulsewatcher.proto.C2SPacket result) {
      result.packetCase_ = packetCase_;
      result.packet_ = this.packet_;
      if (packetCase_ == 2 &&
          registerPacketBuilder_ != null) {
        result.packet_ = registerPacketBuilder_.build();
      }
      if (packetCase_ == 3 &&
          pingPacketBuilder_ != null) {
        result.packet_ = pingPacketBuilder_.build();
      }
      if (packetCase_ == 4 &&
          metricPacketBuilder_ != null) {
        result.packet_ = metricPacketBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof art.ameliah.pulsewatcher.proto.C2SPacket) {
        return mergeFrom((art.ameliah.pulsewatcher.proto.C2SPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(art.ameliah.pulsewatcher.proto.C2SPacket other) {
      if (other == art.ameliah.pulsewatcher.proto.C2SPacket.getDefaultInstance()) return this;
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      switch (other.getPacketCase()) {
        case REGISTERPACKET: {
          mergeRegisterPacket(other.getRegisterPacket());
          break;
        }
        case PINGPACKET: {
          mergePingPacket(other.getPingPacket());
          break;
        }
        case METRICPACKET: {
          mergeMetricPacket(other.getMetricPacket());
          break;
        }
        case PACKET_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              token_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getRegisterPacketFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getPingPacketFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getMetricPacketFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int packetCase_ = 0;
    private java.lang.Object packet_;
    public PacketCase
        getPacketCase() {
      return PacketCase.forNumber(
          packetCase_);
    }

    public Builder clearPacket() {
      packetCase_ = 0;
      packet_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object token_ = "";
    /**
     * <code>string token = 1;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string token = 1;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      token_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string token = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      token_ = getDefaultInstance().getToken();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string token = 1;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      token_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.C2SRegisterPacket, art.ameliah.pulsewatcher.proto.C2SRegisterPacket.Builder, art.ameliah.pulsewatcher.proto.C2SRegisterPacketOrBuilder> registerPacketBuilder_;
    /**
     * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
     * @return Whether the registerPacket field is set.
     */
    @java.lang.Override
    public boolean hasRegisterPacket() {
      return packetCase_ == 2;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
     * @return The registerPacket.
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.C2SRegisterPacket getRegisterPacket() {
      if (registerPacketBuilder_ == null) {
        if (packetCase_ == 2) {
          return (art.ameliah.pulsewatcher.proto.C2SRegisterPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.C2SRegisterPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 2) {
          return registerPacketBuilder_.getMessage();
        }
        return art.ameliah.pulsewatcher.proto.C2SRegisterPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
     */
    public Builder setRegisterPacket(art.ameliah.pulsewatcher.proto.C2SRegisterPacket value) {
      if (registerPacketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        registerPacketBuilder_.setMessage(value);
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
     */
    public Builder setRegisterPacket(
        art.ameliah.pulsewatcher.proto.C2SRegisterPacket.Builder builderForValue) {
      if (registerPacketBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        registerPacketBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
     */
    public Builder mergeRegisterPacket(art.ameliah.pulsewatcher.proto.C2SRegisterPacket value) {
      if (registerPacketBuilder_ == null) {
        if (packetCase_ == 2 &&
            packet_ != art.ameliah.pulsewatcher.proto.C2SRegisterPacket.getDefaultInstance()) {
          packet_ = art.ameliah.pulsewatcher.proto.C2SRegisterPacket.newBuilder((art.ameliah.pulsewatcher.proto.C2SRegisterPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 2) {
          registerPacketBuilder_.mergeFrom(value);
        } else {
          registerPacketBuilder_.setMessage(value);
        }
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
     */
    public Builder clearRegisterPacket() {
      if (registerPacketBuilder_ == null) {
        if (packetCase_ == 2) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 2) {
          packetCase_ = 0;
          packet_ = null;
        }
        registerPacketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
     */
    public art.ameliah.pulsewatcher.proto.C2SRegisterPacket.Builder getRegisterPacketBuilder() {
      return getRegisterPacketFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.C2SRegisterPacketOrBuilder getRegisterPacketOrBuilder() {
      if ((packetCase_ == 2) && (registerPacketBuilder_ != null)) {
        return registerPacketBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 2) {
          return (art.ameliah.pulsewatcher.proto.C2SRegisterPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.C2SRegisterPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SRegisterPacket registerPacket = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.C2SRegisterPacket, art.ameliah.pulsewatcher.proto.C2SRegisterPacket.Builder, art.ameliah.pulsewatcher.proto.C2SRegisterPacketOrBuilder> 
        getRegisterPacketFieldBuilder() {
      if (registerPacketBuilder_ == null) {
        if (!(packetCase_ == 2)) {
          packet_ = art.ameliah.pulsewatcher.proto.C2SRegisterPacket.getDefaultInstance();
        }
        registerPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.pulsewatcher.proto.C2SRegisterPacket, art.ameliah.pulsewatcher.proto.C2SRegisterPacket.Builder, art.ameliah.pulsewatcher.proto.C2SRegisterPacketOrBuilder>(
                (art.ameliah.pulsewatcher.proto.C2SRegisterPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 2;
      onChanged();
      return registerPacketBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.C2SPingPacket, art.ameliah.pulsewatcher.proto.C2SPingPacket.Builder, art.ameliah.pulsewatcher.proto.C2SPingPacketOrBuilder> pingPacketBuilder_;
    /**
     * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
     * @return Whether the pingPacket field is set.
     */
    @java.lang.Override
    public boolean hasPingPacket() {
      return packetCase_ == 3;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
     * @return The pingPacket.
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.C2SPingPacket getPingPacket() {
      if (pingPacketBuilder_ == null) {
        if (packetCase_ == 3) {
          return (art.ameliah.pulsewatcher.proto.C2SPingPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.C2SPingPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 3) {
          return pingPacketBuilder_.getMessage();
        }
        return art.ameliah.pulsewatcher.proto.C2SPingPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
     */
    public Builder setPingPacket(art.ameliah.pulsewatcher.proto.C2SPingPacket value) {
      if (pingPacketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        pingPacketBuilder_.setMessage(value);
      }
      packetCase_ = 3;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
     */
    public Builder setPingPacket(
        art.ameliah.pulsewatcher.proto.C2SPingPacket.Builder builderForValue) {
      if (pingPacketBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        pingPacketBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 3;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
     */
    public Builder mergePingPacket(art.ameliah.pulsewatcher.proto.C2SPingPacket value) {
      if (pingPacketBuilder_ == null) {
        if (packetCase_ == 3 &&
            packet_ != art.ameliah.pulsewatcher.proto.C2SPingPacket.getDefaultInstance()) {
          packet_ = art.ameliah.pulsewatcher.proto.C2SPingPacket.newBuilder((art.ameliah.pulsewatcher.proto.C2SPingPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 3) {
          pingPacketBuilder_.mergeFrom(value);
        } else {
          pingPacketBuilder_.setMessage(value);
        }
      }
      packetCase_ = 3;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
     */
    public Builder clearPingPacket() {
      if (pingPacketBuilder_ == null) {
        if (packetCase_ == 3) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 3) {
          packetCase_ = 0;
          packet_ = null;
        }
        pingPacketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
     */
    public art.ameliah.pulsewatcher.proto.C2SPingPacket.Builder getPingPacketBuilder() {
      return getPingPacketFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.C2SPingPacketOrBuilder getPingPacketOrBuilder() {
      if ((packetCase_ == 3) && (pingPacketBuilder_ != null)) {
        return pingPacketBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 3) {
          return (art.ameliah.pulsewatcher.proto.C2SPingPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.C2SPingPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SPingPacket pingPacket = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.C2SPingPacket, art.ameliah.pulsewatcher.proto.C2SPingPacket.Builder, art.ameliah.pulsewatcher.proto.C2SPingPacketOrBuilder> 
        getPingPacketFieldBuilder() {
      if (pingPacketBuilder_ == null) {
        if (!(packetCase_ == 3)) {
          packet_ = art.ameliah.pulsewatcher.proto.C2SPingPacket.getDefaultInstance();
        }
        pingPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.pulsewatcher.proto.C2SPingPacket, art.ameliah.pulsewatcher.proto.C2SPingPacket.Builder, art.ameliah.pulsewatcher.proto.C2SPingPacketOrBuilder>(
                (art.ameliah.pulsewatcher.proto.C2SPingPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 3;
      onChanged();
      return pingPacketBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.C2SMetricPacket, art.ameliah.pulsewatcher.proto.C2SMetricPacket.Builder, art.ameliah.pulsewatcher.proto.C2SMetricPacketOrBuilder> metricPacketBuilder_;
    /**
     * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
     * @return Whether the metricPacket field is set.
     */
    @java.lang.Override
    public boolean hasMetricPacket() {
      return packetCase_ == 4;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
     * @return The metricPacket.
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.C2SMetricPacket getMetricPacket() {
      if (metricPacketBuilder_ == null) {
        if (packetCase_ == 4) {
          return (art.ameliah.pulsewatcher.proto.C2SMetricPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.C2SMetricPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 4) {
          return metricPacketBuilder_.getMessage();
        }
        return art.ameliah.pulsewatcher.proto.C2SMetricPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
     */
    public Builder setMetricPacket(art.ameliah.pulsewatcher.proto.C2SMetricPacket value) {
      if (metricPacketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        metricPacketBuilder_.setMessage(value);
      }
      packetCase_ = 4;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
     */
    public Builder setMetricPacket(
        art.ameliah.pulsewatcher.proto.C2SMetricPacket.Builder builderForValue) {
      if (metricPacketBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        metricPacketBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 4;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
     */
    public Builder mergeMetricPacket(art.ameliah.pulsewatcher.proto.C2SMetricPacket value) {
      if (metricPacketBuilder_ == null) {
        if (packetCase_ == 4 &&
            packet_ != art.ameliah.pulsewatcher.proto.C2SMetricPacket.getDefaultInstance()) {
          packet_ = art.ameliah.pulsewatcher.proto.C2SMetricPacket.newBuilder((art.ameliah.pulsewatcher.proto.C2SMetricPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 4) {
          metricPacketBuilder_.mergeFrom(value);
        } else {
          metricPacketBuilder_.setMessage(value);
        }
      }
      packetCase_ = 4;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
     */
    public Builder clearMetricPacket() {
      if (metricPacketBuilder_ == null) {
        if (packetCase_ == 4) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 4) {
          packetCase_ = 0;
          packet_ = null;
        }
        metricPacketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
     */
    public art.ameliah.pulsewatcher.proto.C2SMetricPacket.Builder getMetricPacketBuilder() {
      return getMetricPacketFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.C2SMetricPacketOrBuilder getMetricPacketOrBuilder() {
      if ((packetCase_ == 4) && (metricPacketBuilder_ != null)) {
        return metricPacketBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 4) {
          return (art.ameliah.pulsewatcher.proto.C2SMetricPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.C2SMetricPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.C2SMetricPacket metricPacket = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.C2SMetricPacket, art.ameliah.pulsewatcher.proto.C2SMetricPacket.Builder, art.ameliah.pulsewatcher.proto.C2SMetricPacketOrBuilder> 
        getMetricPacketFieldBuilder() {
      if (metricPacketBuilder_ == null) {
        if (!(packetCase_ == 4)) {
          packet_ = art.ameliah.pulsewatcher.proto.C2SMetricPacket.getDefaultInstance();
        }
        metricPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.pulsewatcher.proto.C2SMetricPacket, art.ameliah.pulsewatcher.proto.C2SMetricPacket.Builder, art.ameliah.pulsewatcher.proto.C2SMetricPacketOrBuilder>(
                (art.ameliah.pulsewatcher.proto.C2SMetricPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 4;
      onChanged();
      return metricPacketBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:art.ameliah.pulsewatcher.C2SPacket)
  }

  // @@protoc_insertion_point(class_scope:art.ameliah.pulsewatcher.C2SPacket)
  private static final art.ameliah.pulsewatcher.proto.C2SPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new art.ameliah.pulsewatcher.proto.C2SPacket();
  }

  public static art.ameliah.pulsewatcher.proto.C2SPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<C2SPacket>
      PARSER = new com.google.protobuf.AbstractParser<C2SPacket>() {
    @java.lang.Override
    public C2SPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<C2SPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<C2SPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.C2SPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

