// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public interface C2SRegisterPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.pulsewatcher.C2SRegisterPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.art.ameliah.pulsewatcher.Config config = 3;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.art.ameliah.pulsewatcher.Config config = 3;</code>
   * @return The config.
   */
  art.ameliah.pulsewatcher.proto.Config getConfig();
  /**
   * <code>.art.ameliah.pulsewatcher.Config config = 3;</code>
   */
  art.ameliah.pulsewatcher.proto.ConfigOrBuilder getConfigOrBuilder();

  /**
   * <code>.art.ameliah.pulsewatcher.ClientType clientType = 4;</code>
   * @return The enum numeric value on the wire for clientType.
   */
  int getClientTypeValue();
  /**
   * <code>.art.ameliah.pulsewatcher.ClientType clientType = 4;</code>
   * @return The clientType.
   */
  art.ameliah.pulsewatcher.proto.ClientType getClientType();
}
