// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

/**
 * Protobuf enum {@code art.ameliah.pulsewatcher.ClientType}
 */
public enum ClientType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>API_CLIENT = 0;</code>
   */
  API_CLIENT(0),
  /**
   * <code>WEB_CLIENT = 1;</code>
   */
  WEB_CLIENT(1),
  /**
   * <code>DC_BOT_CLIENT = 2;</code>
   */
  DC_BOT_CLIENT(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>API_CLIENT = 0;</code>
   */
  public static final int API_CLIENT_VALUE = 0;
  /**
   * <code>WEB_CLIENT = 1;</code>
   */
  public static final int WEB_CLIENT_VALUE = 1;
  /**
   * <code>DC_BOT_CLIENT = 2;</code>
   */
  public static final int DC_BOT_CLIENT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ClientType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ClientType forNumber(int value) {
    switch (value) {
      case 0: return API_CLIENT;
      case 1: return WEB_CLIENT;
      case 2: return DC_BOT_CLIENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ClientType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ClientType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ClientType>() {
          public ClientType findValueByNumber(int number) {
            return ClientType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return art.ameliah.pulsewatcher.proto.Packets.getDescriptor().getEnumTypes().get(0);
  }

  private static final ClientType[] VALUES = values();

  public static ClientType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ClientType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:art.ameliah.pulsewatcher.ClientType)
}

