// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public interface MutableConfigFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.pulsewatcher.MutableConfigField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string currentValue = 2;</code>
   * @return The currentValue.
   */
  java.lang.String getCurrentValue();
  /**
   * <code>string currentValue = 2;</code>
   * @return The bytes for currentValue.
   */
  com.google.protobuf.ByteString
      getCurrentValueBytes();
}
