// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public final class Packets {
  private Packets() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_S2CPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_S2CPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_C2SPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_C2SPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_S2CRegisterPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_S2CRegisterPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_C2SRegisterPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_C2SRegisterPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_ConfigField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_ConfigField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_MutableConfigField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_MutableConfigField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_S2CPingPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_S2CPingPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_C2SPingPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_C2SPingPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_S2CMetricPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_S2CMetricPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_C2SMetricPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_C2SMetricPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_APIClientMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_APIClientMetric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpackets.proto\022\030art.ameliah.pulsewatche" +
      "r\032\037google/protobuf/timestamp.proto\"\336\001\n\tS" +
      "2CPacket\022E\n\016registerPacket\030\001 \001(\0132+.art.a" +
      "meliah.pulsewatcher.S2CRegisterPacketH\000\022" +
      "=\n\npingPacket\030\002 \001(\0132\'.art.ameliah.pulsew" +
      "atcher.S2CPingPacketH\000\022A\n\014metricPacket\030\003" +
      " \001(\0132).art.ameliah.pulsewatcher.S2CMetri" +
      "cPacketH\000B\010\n\006packet\"\355\001\n\tC2SPacket\022\r\n\005tok" +
      "en\030\001 \001(\t\022E\n\016registerPacket\030\002 \001(\0132+.art.a" +
      "meliah.pulsewatcher.C2SRegisterPacketH\000\022" +
      "=\n\npingPacket\030\003 \001(\0132\'.art.ameliah.pulsew" +
      "atcher.C2SPingPacketH\000\022A\n\014metricPacket\030\004" +
      " \001(\0132).art.ameliah.pulsewatcher.C2SMetri" +
      "cPacketH\000B\010\n\006packet\"\"\n\021S2CRegisterPacket" +
      "\022\r\n\005token\030\001 \001(\t\"\234\001\n\021C2SRegisterPacket\022\r\n" +
      "\005token\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\0220\n\006config\030\003 \001" +
      "(\0132 .art.ameliah.pulsewatcher.Config\0228\n\n" +
      "clientType\030\004 \001(\0162$.art.ameliah.pulsewatc" +
      "her.ClientType\"\204\001\n\006Config\0225\n\006fields\030\001 \003(" +
      "\0132%.art.ameliah.pulsewatcher.ConfigField" +
      "\022C\n\rmutableFields\030\002 \003(\0132,.art.ameliah.pu" +
      "lsewatcher.MutableConfigField\"*\n\013ConfigF" +
      "ield\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"8\n\022Mut" +
      "ableConfigField\022\014\n\004name\030\001 \001(\t\022\024\n\014current" +
      "Value\030\002 \001(\t\">\n\rS2CPingPacket\022-\n\ttimestam" +
      "p\030\001 \001(\0132\032.google.protobuf.Timestamp\">\n\rC" +
      "2SPingPacket\022-\n\ttimestamp\030\001 \001(\0132\032.google" +
      ".protobuf.Timestamp\"\021\n\017S2CMetricPacket\"\204" +
      "\001\n\017C2SMetricPacket\022\020\n\010ramUsage\030\001 \001(\003\022\016\n\006" +
      "uptime\030\002 \001(\003\022D\n\017apiClientMetric\030\003 \001(\0132)." +
      "art.ameliah.pulsewatcher.APIClientMetric" +
      "H\000B\t\n\007metrics\"\202\001\n\017APIClientMetric\022\014\n\004hos" +
      "t\030\001 \001(\t\022\n\n\002os\030\002 \001(\t\022\014\n\004port\030\003 \001(\t\022G\n\022api" +
      "EndPointMetrics\030\004 \003(\0132+.art.ameliah.puls" +
      "ewatcher.APIEndPointMetric\"C\n\021APIEndPoin" +
      "tMetric\022\020\n\010endPoint\030\001 \001(\t\022\014\n\004hits\030\002 \001(\003\022" +
      "\016\n\006errors\030\003 \001(\003*?\n\nClientType\022\016\n\nAPI_CLI" +
      "ENT\020\000\022\016\n\nWEB_CLIENT\020\001\022\021\n\rDC_BOT_CLIENT\020\002" +
      "B:\n\036art.ameliah.pulsewatcher.protoB\007Pack" +
      "etsP\001Z\rproto/packetsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_art_ameliah_pulsewatcher_S2CPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_art_ameliah_pulsewatcher_S2CPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_S2CPacket_descriptor,
        new java.lang.String[] { "RegisterPacket", "PingPacket", "MetricPacket", "Packet", });
    internal_static_art_ameliah_pulsewatcher_C2SPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_art_ameliah_pulsewatcher_C2SPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_C2SPacket_descriptor,
        new java.lang.String[] { "Token", "RegisterPacket", "PingPacket", "MetricPacket", "Packet", });
    internal_static_art_ameliah_pulsewatcher_S2CRegisterPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_art_ameliah_pulsewatcher_S2CRegisterPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_S2CRegisterPacket_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_art_ameliah_pulsewatcher_C2SRegisterPacket_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_art_ameliah_pulsewatcher_C2SRegisterPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_C2SRegisterPacket_descriptor,
        new java.lang.String[] { "Token", "Name", "Config", "ClientType", });
    internal_static_art_ameliah_pulsewatcher_Config_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_art_ameliah_pulsewatcher_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_Config_descriptor,
        new java.lang.String[] { "Fields", "MutableFields", });
    internal_static_art_ameliah_pulsewatcher_ConfigField_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_art_ameliah_pulsewatcher_ConfigField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_ConfigField_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_art_ameliah_pulsewatcher_MutableConfigField_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_art_ameliah_pulsewatcher_MutableConfigField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_MutableConfigField_descriptor,
        new java.lang.String[] { "Name", "CurrentValue", });
    internal_static_art_ameliah_pulsewatcher_S2CPingPacket_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_art_ameliah_pulsewatcher_S2CPingPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_S2CPingPacket_descriptor,
        new java.lang.String[] { "Timestamp", });
    internal_static_art_ameliah_pulsewatcher_C2SPingPacket_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_art_ameliah_pulsewatcher_C2SPingPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_C2SPingPacket_descriptor,
        new java.lang.String[] { "Timestamp", });
    internal_static_art_ameliah_pulsewatcher_S2CMetricPacket_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_art_ameliah_pulsewatcher_S2CMetricPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_S2CMetricPacket_descriptor,
        new java.lang.String[] { });
    internal_static_art_ameliah_pulsewatcher_C2SMetricPacket_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_art_ameliah_pulsewatcher_C2SMetricPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_C2SMetricPacket_descriptor,
        new java.lang.String[] { "RamUsage", "Uptime", "ApiClientMetric", "Metrics", });
    internal_static_art_ameliah_pulsewatcher_APIClientMetric_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_art_ameliah_pulsewatcher_APIClientMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_APIClientMetric_descriptor,
        new java.lang.String[] { "Host", "Os", "Port", "ApiEndPointMetrics", });
    internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_art_ameliah_pulsewatcher_APIEndPointMetric_descriptor,
        new java.lang.String[] { "EndPoint", "Hits", "Errors", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
