// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public interface S2CChangeConfigPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.pulsewatcher.S2CChangeConfigPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
   * @return Whether the configField field is set.
   */
  boolean hasConfigField();
  /**
   * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
   * @return The configField.
   */
  art.ameliah.pulsewatcher.proto.MutableConfigField getConfigField();
  /**
   * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
   */
  art.ameliah.pulsewatcher.proto.MutableConfigFieldOrBuilder getConfigFieldOrBuilder();
}
