// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

/**
 * Protobuf type {@code art.ameliah.pulsewatcher.S2CChangeConfigPacket}
 */
public final class S2CChangeConfigPacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:art.ameliah.pulsewatcher.S2CChangeConfigPacket)
    S2CChangeConfigPacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use S2CChangeConfigPacket.newBuilder() to construct.
  private S2CChangeConfigPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private S2CChangeConfigPacket() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new S2CChangeConfigPacket();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CChangeConfigPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CChangeConfigPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket.class, art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket.Builder.class);
  }

  private int bitField0_;
  public static final int CONFIGFIELD_FIELD_NUMBER = 1;
  private art.ameliah.pulsewatcher.proto.MutableConfigField configField_;
  /**
   * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
   * @return Whether the configField field is set.
   */
  @java.lang.Override
  public boolean hasConfigField() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
   * @return The configField.
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.MutableConfigField getConfigField() {
    return configField_ == null ? art.ameliah.pulsewatcher.proto.MutableConfigField.getDefaultInstance() : configField_;
  }
  /**
   * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.MutableConfigFieldOrBuilder getConfigFieldOrBuilder() {
    return configField_ == null ? art.ameliah.pulsewatcher.proto.MutableConfigField.getDefaultInstance() : configField_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getConfigField());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getConfigField());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket)) {
      return super.equals(obj);
    }
    art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket other = (art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket) obj;

    if (hasConfigField() != other.hasConfigField()) return false;
    if (hasConfigField()) {
      if (!getConfigField()
          .equals(other.getConfigField())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasConfigField()) {
      hash = (37 * hash) + CONFIGFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getConfigField().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code art.ameliah.pulsewatcher.S2CChangeConfigPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:art.ameliah.pulsewatcher.S2CChangeConfigPacket)
      art.ameliah.pulsewatcher.proto.S2CChangeConfigPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CChangeConfigPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CChangeConfigPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket.class, art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket.Builder.class);
    }

    // Construct using art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConfigFieldFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      configField_ = null;
      if (configFieldBuilder_ != null) {
        configFieldBuilder_.dispose();
        configFieldBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CChangeConfigPacket_descriptor;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket getDefaultInstanceForType() {
      return art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket.getDefaultInstance();
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket build() {
      art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket buildPartial() {
      art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket result = new art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.configField_ = configFieldBuilder_ == null
            ? configField_
            : configFieldBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket) {
        return mergeFrom((art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket other) {
      if (other == art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket.getDefaultInstance()) return this;
      if (other.hasConfigField()) {
        mergeConfigField(other.getConfigField());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getConfigFieldFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private art.ameliah.pulsewatcher.proto.MutableConfigField configField_;
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.MutableConfigField, art.ameliah.pulsewatcher.proto.MutableConfigField.Builder, art.ameliah.pulsewatcher.proto.MutableConfigFieldOrBuilder> configFieldBuilder_;
    /**
     * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
     * @return Whether the configField field is set.
     */
    public boolean hasConfigField() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
     * @return The configField.
     */
    public art.ameliah.pulsewatcher.proto.MutableConfigField getConfigField() {
      if (configFieldBuilder_ == null) {
        return configField_ == null ? art.ameliah.pulsewatcher.proto.MutableConfigField.getDefaultInstance() : configField_;
      } else {
        return configFieldBuilder_.getMessage();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
     */
    public Builder setConfigField(art.ameliah.pulsewatcher.proto.MutableConfigField value) {
      if (configFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        configField_ = value;
      } else {
        configFieldBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
     */
    public Builder setConfigField(
        art.ameliah.pulsewatcher.proto.MutableConfigField.Builder builderForValue) {
      if (configFieldBuilder_ == null) {
        configField_ = builderForValue.build();
      } else {
        configFieldBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
     */
    public Builder mergeConfigField(art.ameliah.pulsewatcher.proto.MutableConfigField value) {
      if (configFieldBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          configField_ != null &&
          configField_ != art.ameliah.pulsewatcher.proto.MutableConfigField.getDefaultInstance()) {
          getConfigFieldBuilder().mergeFrom(value);
        } else {
          configField_ = value;
        }
      } else {
        configFieldBuilder_.mergeFrom(value);
      }
      if (configField_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
     */
    public Builder clearConfigField() {
      bitField0_ = (bitField0_ & ~0x00000001);
      configField_ = null;
      if (configFieldBuilder_ != null) {
        configFieldBuilder_.dispose();
        configFieldBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
     */
    public art.ameliah.pulsewatcher.proto.MutableConfigField.Builder getConfigFieldBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getConfigFieldFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
     */
    public art.ameliah.pulsewatcher.proto.MutableConfigFieldOrBuilder getConfigFieldOrBuilder() {
      if (configFieldBuilder_ != null) {
        return configFieldBuilder_.getMessageOrBuilder();
      } else {
        return configField_ == null ?
            art.ameliah.pulsewatcher.proto.MutableConfigField.getDefaultInstance() : configField_;
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.MutableConfigField configField = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.MutableConfigField, art.ameliah.pulsewatcher.proto.MutableConfigField.Builder, art.ameliah.pulsewatcher.proto.MutableConfigFieldOrBuilder> 
        getConfigFieldFieldBuilder() {
      if (configFieldBuilder_ == null) {
        configFieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.pulsewatcher.proto.MutableConfigField, art.ameliah.pulsewatcher.proto.MutableConfigField.Builder, art.ameliah.pulsewatcher.proto.MutableConfigFieldOrBuilder>(
                getConfigField(),
                getParentForChildren(),
                isClean());
        configField_ = null;
      }
      return configFieldBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:art.ameliah.pulsewatcher.S2CChangeConfigPacket)
  }

  // @@protoc_insertion_point(class_scope:art.ameliah.pulsewatcher.S2CChangeConfigPacket)
  private static final art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket();
  }

  public static art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<S2CChangeConfigPacket>
      PARSER = new com.google.protobuf.AbstractParser<S2CChangeConfigPacket>() {
    @java.lang.Override
    public S2CChangeConfigPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<S2CChangeConfigPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<S2CChangeConfigPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.S2CChangeConfigPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

