// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

public interface S2CMetricPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.pulsewatcher.S2CMetricPacket)
    com.google.protobuf.MessageOrBuilder {
}
