// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.1
package art.ameliah.pulsewatcher.proto;

/**
 * Protobuf type {@code art.ameliah.pulsewatcher.S2CPacket}
 */
public final class S2CPacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:art.ameliah.pulsewatcher.S2CPacket)
    S2CPacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use S2CPacket.newBuilder() to construct.
  private S2CPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private S2CPacket() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new S2CPacket();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            art.ameliah.pulsewatcher.proto.S2CPacket.class, art.ameliah.pulsewatcher.proto.S2CPacket.Builder.class);
  }

  private int packetCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object packet_;
  public enum PacketCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    REGISTERPACKET(1),
    PINGPACKET(2),
    METRICPACKET(3),
    PACKET_NOT_SET(0);
    private final int value;
    private PacketCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketCase valueOf(int value) {
      return forNumber(value);
    }

    public static PacketCase forNumber(int value) {
      switch (value) {
        case 1: return REGISTERPACKET;
        case 2: return PINGPACKET;
        case 3: return METRICPACKET;
        case 0: return PACKET_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PacketCase
  getPacketCase() {
    return PacketCase.forNumber(
        packetCase_);
  }

  public static final int REGISTERPACKET_FIELD_NUMBER = 1;
  /**
   * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
   * @return Whether the registerPacket field is set.
   */
  @java.lang.Override
  public boolean hasRegisterPacket() {
    return packetCase_ == 1;
  }
  /**
   * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
   * @return The registerPacket.
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.S2CRegisterPacket getRegisterPacket() {
    if (packetCase_ == 1) {
       return (art.ameliah.pulsewatcher.proto.S2CRegisterPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.S2CRegisterPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.S2CRegisterPacketOrBuilder getRegisterPacketOrBuilder() {
    if (packetCase_ == 1) {
       return (art.ameliah.pulsewatcher.proto.S2CRegisterPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.S2CRegisterPacket.getDefaultInstance();
  }

  public static final int PINGPACKET_FIELD_NUMBER = 2;
  /**
   * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
   * @return Whether the pingPacket field is set.
   */
  @java.lang.Override
  public boolean hasPingPacket() {
    return packetCase_ == 2;
  }
  /**
   * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
   * @return The pingPacket.
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.S2CPingPacket getPingPacket() {
    if (packetCase_ == 2) {
       return (art.ameliah.pulsewatcher.proto.S2CPingPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.S2CPingPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.S2CPingPacketOrBuilder getPingPacketOrBuilder() {
    if (packetCase_ == 2) {
       return (art.ameliah.pulsewatcher.proto.S2CPingPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.S2CPingPacket.getDefaultInstance();
  }

  public static final int METRICPACKET_FIELD_NUMBER = 3;
  /**
   * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
   * @return Whether the metricPacket field is set.
   */
  @java.lang.Override
  public boolean hasMetricPacket() {
    return packetCase_ == 3;
  }
  /**
   * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
   * @return The metricPacket.
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.S2CMetricPacket getMetricPacket() {
    if (packetCase_ == 3) {
       return (art.ameliah.pulsewatcher.proto.S2CMetricPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.S2CMetricPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
   */
  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.S2CMetricPacketOrBuilder getMetricPacketOrBuilder() {
    if (packetCase_ == 3) {
       return (art.ameliah.pulsewatcher.proto.S2CMetricPacket) packet_;
    }
    return art.ameliah.pulsewatcher.proto.S2CMetricPacket.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (packetCase_ == 1) {
      output.writeMessage(1, (art.ameliah.pulsewatcher.proto.S2CRegisterPacket) packet_);
    }
    if (packetCase_ == 2) {
      output.writeMessage(2, (art.ameliah.pulsewatcher.proto.S2CPingPacket) packet_);
    }
    if (packetCase_ == 3) {
      output.writeMessage(3, (art.ameliah.pulsewatcher.proto.S2CMetricPacket) packet_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (packetCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (art.ameliah.pulsewatcher.proto.S2CRegisterPacket) packet_);
    }
    if (packetCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (art.ameliah.pulsewatcher.proto.S2CPingPacket) packet_);
    }
    if (packetCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (art.ameliah.pulsewatcher.proto.S2CMetricPacket) packet_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof art.ameliah.pulsewatcher.proto.S2CPacket)) {
      return super.equals(obj);
    }
    art.ameliah.pulsewatcher.proto.S2CPacket other = (art.ameliah.pulsewatcher.proto.S2CPacket) obj;

    if (!getPacketCase().equals(other.getPacketCase())) return false;
    switch (packetCase_) {
      case 1:
        if (!getRegisterPacket()
            .equals(other.getRegisterPacket())) return false;
        break;
      case 2:
        if (!getPingPacket()
            .equals(other.getPingPacket())) return false;
        break;
      case 3:
        if (!getMetricPacket()
            .equals(other.getMetricPacket())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (packetCase_) {
      case 1:
        hash = (37 * hash) + REGISTERPACKET_FIELD_NUMBER;
        hash = (53 * hash) + getRegisterPacket().hashCode();
        break;
      case 2:
        hash = (37 * hash) + PINGPACKET_FIELD_NUMBER;
        hash = (53 * hash) + getPingPacket().hashCode();
        break;
      case 3:
        hash = (37 * hash) + METRICPACKET_FIELD_NUMBER;
        hash = (53 * hash) + getMetricPacket().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static art.ameliah.pulsewatcher.proto.S2CPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static art.ameliah.pulsewatcher.proto.S2CPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.pulsewatcher.proto.S2CPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(art.ameliah.pulsewatcher.proto.S2CPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code art.ameliah.pulsewatcher.S2CPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:art.ameliah.pulsewatcher.S2CPacket)
      art.ameliah.pulsewatcher.proto.S2CPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              art.ameliah.pulsewatcher.proto.S2CPacket.class, art.ameliah.pulsewatcher.proto.S2CPacket.Builder.class);
    }

    // Construct using art.ameliah.pulsewatcher.proto.S2CPacket.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (registerPacketBuilder_ != null) {
        registerPacketBuilder_.clear();
      }
      if (pingPacketBuilder_ != null) {
        pingPacketBuilder_.clear();
      }
      if (metricPacketBuilder_ != null) {
        metricPacketBuilder_.clear();
      }
      packetCase_ = 0;
      packet_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return art.ameliah.pulsewatcher.proto.Packets.internal_static_art_ameliah_pulsewatcher_S2CPacket_descriptor;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CPacket getDefaultInstanceForType() {
      return art.ameliah.pulsewatcher.proto.S2CPacket.getDefaultInstance();
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CPacket build() {
      art.ameliah.pulsewatcher.proto.S2CPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CPacket buildPartial() {
      art.ameliah.pulsewatcher.proto.S2CPacket result = new art.ameliah.pulsewatcher.proto.S2CPacket(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(art.ameliah.pulsewatcher.proto.S2CPacket result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(art.ameliah.pulsewatcher.proto.S2CPacket result) {
      result.packetCase_ = packetCase_;
      result.packet_ = this.packet_;
      if (packetCase_ == 1 &&
          registerPacketBuilder_ != null) {
        result.packet_ = registerPacketBuilder_.build();
      }
      if (packetCase_ == 2 &&
          pingPacketBuilder_ != null) {
        result.packet_ = pingPacketBuilder_.build();
      }
      if (packetCase_ == 3 &&
          metricPacketBuilder_ != null) {
        result.packet_ = metricPacketBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof art.ameliah.pulsewatcher.proto.S2CPacket) {
        return mergeFrom((art.ameliah.pulsewatcher.proto.S2CPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(art.ameliah.pulsewatcher.proto.S2CPacket other) {
      if (other == art.ameliah.pulsewatcher.proto.S2CPacket.getDefaultInstance()) return this;
      switch (other.getPacketCase()) {
        case REGISTERPACKET: {
          mergeRegisterPacket(other.getRegisterPacket());
          break;
        }
        case PINGPACKET: {
          mergePingPacket(other.getPingPacket());
          break;
        }
        case METRICPACKET: {
          mergeMetricPacket(other.getMetricPacket());
          break;
        }
        case PACKET_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRegisterPacketFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPingPacketFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getMetricPacketFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int packetCase_ = 0;
    private java.lang.Object packet_;
    public PacketCase
        getPacketCase() {
      return PacketCase.forNumber(
          packetCase_);
    }

    public Builder clearPacket() {
      packetCase_ = 0;
      packet_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.S2CRegisterPacket, art.ameliah.pulsewatcher.proto.S2CRegisterPacket.Builder, art.ameliah.pulsewatcher.proto.S2CRegisterPacketOrBuilder> registerPacketBuilder_;
    /**
     * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
     * @return Whether the registerPacket field is set.
     */
    @java.lang.Override
    public boolean hasRegisterPacket() {
      return packetCase_ == 1;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
     * @return The registerPacket.
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CRegisterPacket getRegisterPacket() {
      if (registerPacketBuilder_ == null) {
        if (packetCase_ == 1) {
          return (art.ameliah.pulsewatcher.proto.S2CRegisterPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.S2CRegisterPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 1) {
          return registerPacketBuilder_.getMessage();
        }
        return art.ameliah.pulsewatcher.proto.S2CRegisterPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
     */
    public Builder setRegisterPacket(art.ameliah.pulsewatcher.proto.S2CRegisterPacket value) {
      if (registerPacketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        registerPacketBuilder_.setMessage(value);
      }
      packetCase_ = 1;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
     */
    public Builder setRegisterPacket(
        art.ameliah.pulsewatcher.proto.S2CRegisterPacket.Builder builderForValue) {
      if (registerPacketBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        registerPacketBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 1;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
     */
    public Builder mergeRegisterPacket(art.ameliah.pulsewatcher.proto.S2CRegisterPacket value) {
      if (registerPacketBuilder_ == null) {
        if (packetCase_ == 1 &&
            packet_ != art.ameliah.pulsewatcher.proto.S2CRegisterPacket.getDefaultInstance()) {
          packet_ = art.ameliah.pulsewatcher.proto.S2CRegisterPacket.newBuilder((art.ameliah.pulsewatcher.proto.S2CRegisterPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 1) {
          registerPacketBuilder_.mergeFrom(value);
        } else {
          registerPacketBuilder_.setMessage(value);
        }
      }
      packetCase_ = 1;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
     */
    public Builder clearRegisterPacket() {
      if (registerPacketBuilder_ == null) {
        if (packetCase_ == 1) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 1) {
          packetCase_ = 0;
          packet_ = null;
        }
        registerPacketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
     */
    public art.ameliah.pulsewatcher.proto.S2CRegisterPacket.Builder getRegisterPacketBuilder() {
      return getRegisterPacketFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CRegisterPacketOrBuilder getRegisterPacketOrBuilder() {
      if ((packetCase_ == 1) && (registerPacketBuilder_ != null)) {
        return registerPacketBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 1) {
          return (art.ameliah.pulsewatcher.proto.S2CRegisterPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.S2CRegisterPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CRegisterPacket registerPacket = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.S2CRegisterPacket, art.ameliah.pulsewatcher.proto.S2CRegisterPacket.Builder, art.ameliah.pulsewatcher.proto.S2CRegisterPacketOrBuilder> 
        getRegisterPacketFieldBuilder() {
      if (registerPacketBuilder_ == null) {
        if (!(packetCase_ == 1)) {
          packet_ = art.ameliah.pulsewatcher.proto.S2CRegisterPacket.getDefaultInstance();
        }
        registerPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.pulsewatcher.proto.S2CRegisterPacket, art.ameliah.pulsewatcher.proto.S2CRegisterPacket.Builder, art.ameliah.pulsewatcher.proto.S2CRegisterPacketOrBuilder>(
                (art.ameliah.pulsewatcher.proto.S2CRegisterPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 1;
      onChanged();
      return registerPacketBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.S2CPingPacket, art.ameliah.pulsewatcher.proto.S2CPingPacket.Builder, art.ameliah.pulsewatcher.proto.S2CPingPacketOrBuilder> pingPacketBuilder_;
    /**
     * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
     * @return Whether the pingPacket field is set.
     */
    @java.lang.Override
    public boolean hasPingPacket() {
      return packetCase_ == 2;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
     * @return The pingPacket.
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CPingPacket getPingPacket() {
      if (pingPacketBuilder_ == null) {
        if (packetCase_ == 2) {
          return (art.ameliah.pulsewatcher.proto.S2CPingPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.S2CPingPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 2) {
          return pingPacketBuilder_.getMessage();
        }
        return art.ameliah.pulsewatcher.proto.S2CPingPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
     */
    public Builder setPingPacket(art.ameliah.pulsewatcher.proto.S2CPingPacket value) {
      if (pingPacketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        pingPacketBuilder_.setMessage(value);
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
     */
    public Builder setPingPacket(
        art.ameliah.pulsewatcher.proto.S2CPingPacket.Builder builderForValue) {
      if (pingPacketBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        pingPacketBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
     */
    public Builder mergePingPacket(art.ameliah.pulsewatcher.proto.S2CPingPacket value) {
      if (pingPacketBuilder_ == null) {
        if (packetCase_ == 2 &&
            packet_ != art.ameliah.pulsewatcher.proto.S2CPingPacket.getDefaultInstance()) {
          packet_ = art.ameliah.pulsewatcher.proto.S2CPingPacket.newBuilder((art.ameliah.pulsewatcher.proto.S2CPingPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 2) {
          pingPacketBuilder_.mergeFrom(value);
        } else {
          pingPacketBuilder_.setMessage(value);
        }
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
     */
    public Builder clearPingPacket() {
      if (pingPacketBuilder_ == null) {
        if (packetCase_ == 2) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 2) {
          packetCase_ = 0;
          packet_ = null;
        }
        pingPacketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
     */
    public art.ameliah.pulsewatcher.proto.S2CPingPacket.Builder getPingPacketBuilder() {
      return getPingPacketFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CPingPacketOrBuilder getPingPacketOrBuilder() {
      if ((packetCase_ == 2) && (pingPacketBuilder_ != null)) {
        return pingPacketBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 2) {
          return (art.ameliah.pulsewatcher.proto.S2CPingPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.S2CPingPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CPingPacket pingPacket = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.S2CPingPacket, art.ameliah.pulsewatcher.proto.S2CPingPacket.Builder, art.ameliah.pulsewatcher.proto.S2CPingPacketOrBuilder> 
        getPingPacketFieldBuilder() {
      if (pingPacketBuilder_ == null) {
        if (!(packetCase_ == 2)) {
          packet_ = art.ameliah.pulsewatcher.proto.S2CPingPacket.getDefaultInstance();
        }
        pingPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.pulsewatcher.proto.S2CPingPacket, art.ameliah.pulsewatcher.proto.S2CPingPacket.Builder, art.ameliah.pulsewatcher.proto.S2CPingPacketOrBuilder>(
                (art.ameliah.pulsewatcher.proto.S2CPingPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 2;
      onChanged();
      return pingPacketBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.S2CMetricPacket, art.ameliah.pulsewatcher.proto.S2CMetricPacket.Builder, art.ameliah.pulsewatcher.proto.S2CMetricPacketOrBuilder> metricPacketBuilder_;
    /**
     * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
     * @return Whether the metricPacket field is set.
     */
    @java.lang.Override
    public boolean hasMetricPacket() {
      return packetCase_ == 3;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
     * @return The metricPacket.
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CMetricPacket getMetricPacket() {
      if (metricPacketBuilder_ == null) {
        if (packetCase_ == 3) {
          return (art.ameliah.pulsewatcher.proto.S2CMetricPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.S2CMetricPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 3) {
          return metricPacketBuilder_.getMessage();
        }
        return art.ameliah.pulsewatcher.proto.S2CMetricPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
     */
    public Builder setMetricPacket(art.ameliah.pulsewatcher.proto.S2CMetricPacket value) {
      if (metricPacketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        metricPacketBuilder_.setMessage(value);
      }
      packetCase_ = 3;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
     */
    public Builder setMetricPacket(
        art.ameliah.pulsewatcher.proto.S2CMetricPacket.Builder builderForValue) {
      if (metricPacketBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        metricPacketBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 3;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
     */
    public Builder mergeMetricPacket(art.ameliah.pulsewatcher.proto.S2CMetricPacket value) {
      if (metricPacketBuilder_ == null) {
        if (packetCase_ == 3 &&
            packet_ != art.ameliah.pulsewatcher.proto.S2CMetricPacket.getDefaultInstance()) {
          packet_ = art.ameliah.pulsewatcher.proto.S2CMetricPacket.newBuilder((art.ameliah.pulsewatcher.proto.S2CMetricPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 3) {
          metricPacketBuilder_.mergeFrom(value);
        } else {
          metricPacketBuilder_.setMessage(value);
        }
      }
      packetCase_ = 3;
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
     */
    public Builder clearMetricPacket() {
      if (metricPacketBuilder_ == null) {
        if (packetCase_ == 3) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 3) {
          packetCase_ = 0;
          packet_ = null;
        }
        metricPacketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
     */
    public art.ameliah.pulsewatcher.proto.S2CMetricPacket.Builder getMetricPacketBuilder() {
      return getMetricPacketFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
     */
    @java.lang.Override
    public art.ameliah.pulsewatcher.proto.S2CMetricPacketOrBuilder getMetricPacketOrBuilder() {
      if ((packetCase_ == 3) && (metricPacketBuilder_ != null)) {
        return metricPacketBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 3) {
          return (art.ameliah.pulsewatcher.proto.S2CMetricPacket) packet_;
        }
        return art.ameliah.pulsewatcher.proto.S2CMetricPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.pulsewatcher.S2CMetricPacket metricPacket = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.pulsewatcher.proto.S2CMetricPacket, art.ameliah.pulsewatcher.proto.S2CMetricPacket.Builder, art.ameliah.pulsewatcher.proto.S2CMetricPacketOrBuilder> 
        getMetricPacketFieldBuilder() {
      if (metricPacketBuilder_ == null) {
        if (!(packetCase_ == 3)) {
          packet_ = art.ameliah.pulsewatcher.proto.S2CMetricPacket.getDefaultInstance();
        }
        metricPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.pulsewatcher.proto.S2CMetricPacket, art.ameliah.pulsewatcher.proto.S2CMetricPacket.Builder, art.ameliah.pulsewatcher.proto.S2CMetricPacketOrBuilder>(
                (art.ameliah.pulsewatcher.proto.S2CMetricPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 3;
      onChanged();
      return metricPacketBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:art.ameliah.pulsewatcher.S2CPacket)
  }

  // @@protoc_insertion_point(class_scope:art.ameliah.pulsewatcher.S2CPacket)
  private static final art.ameliah.pulsewatcher.proto.S2CPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new art.ameliah.pulsewatcher.proto.S2CPacket();
  }

  public static art.ameliah.pulsewatcher.proto.S2CPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<S2CPacket>
      PARSER = new com.google.protobuf.AbstractParser<S2CPacket>() {
    @java.lang.Override
    public S2CPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<S2CPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<S2CPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public art.ameliah.pulsewatcher.proto.S2CPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

