services:
  erasmusbot:
    image: erasmusbot
    restart: "on-failure:3"
    volumes:
      - "./erasmusbot-config.yaml:/app/config.yaml"
      - "./erasmusbot-db.db:/app/erasmus_bot.db"
    ports:
      - "80:80"